"""Seed documented provider capability records without promoting them.

Seed data is a policy catalogue, not live reachability or benchmark evidence.
Operational promotion must happen through explicit capability evidence.
"""

from __future__ import annotations

from app.schemas.v3_registry import ModelRecord
from app.services.v3_model_registry import ModelRegistry


def build_seeded_registry() -> ModelRegistry:
    """Return deterministic documented records; none are enabled by seeding."""
    return ModelRegistry(
        [
            ModelRecord(
                provider="deepseek",
                provider_model_id="deepseek-v4-flash",
                display_name="DeepSeek V4 Flash",
                capability_tier="flash",
                context_window=128_000,
                max_output=8_192,
                input_modalities=["text"],
                tool_support=True,
                structured_output_support=True,
                reasoning_efforts=["none", "high"],
                speed_class="fast",
                cost_metadata_version="session13-v1",
                availability="available",
                calibration_status="documented",
            ),
            ModelRecord(
                provider="deepseek",
                provider_model_id="deepseek-v4-pro",
                display_name="DeepSeek V4 Pro",
                capability_tier="pro",
                context_window=128_000,
                max_output=8_192,
                input_modalities=["text"],
                tool_support=True,
                structured_output_support=True,
                reasoning_efforts=["none", "high", "max"],
                speed_class="fast",
                cost_metadata_version="session13-v1",
                availability="available",
                calibration_status="documented",
            ),
            ModelRecord(
                provider="moonshot",
                provider_model_id="kimi-for-coding",
                display_name="Kimi K2.7 Code",
                capability_tier="pro",
                context_window=256_000,
                max_output=8_192,
                input_modalities=["text"],
                tool_support=True,
                structured_output_support=True,
                reasoning_efforts=["high"],
                speed_class="medium",
                cost_metadata_version="session13-v2",
                availability="available",
                calibration_status="documented",
            ),
            ModelRecord(
                provider="moonshot",
                provider_model_id="kimi-for-coding-highspeed",
                display_name="Kimi K2.7 Code HighSpeed",
                capability_tier="pro",
                context_window=256_000,
                max_output=8_192,
                input_modalities=["text"],
                tool_support=True,
                structured_output_support=True,
                reasoning_efforts=["high"],
                speed_class="fast",
                cost_metadata_version="session13-v2",
                availability="available",
                calibration_status="documented",
            ),
            ModelRecord(
                provider="moonshot",
                provider_model_id="k3",
                display_name="Kimi K3",
                capability_tier="max",
                context_window=1_000_000,
                max_output=8_192,
                input_modalities=["text", "image"],
                tool_support=True,
                structured_output_support=True,
                reasoning_efforts=["low", "high", "max"],
                speed_class="medium",
                cost_metadata_version="session13-v2",
                availability="available",
                calibration_status="documented",
            ),
            ModelRecord(
                provider="openai",
                provider_model_id="gpt-5.6-luna",
                display_name="GPT-5.6 Luna",
                capability_tier="flash",
                context_window=128_000,
                max_output=16_384,
                input_modalities=["text"],
                tool_support=True,
                structured_output_support=True,
                reasoning_efforts=["none", "high"],
                speed_class="fast",
                cost_metadata_version="session13-v1",
                availability="available",
                calibration_status="documented",
            ),
            ModelRecord(
                provider="openai",
                provider_model_id="gpt-5.6-terra",
                display_name="GPT-5.6 Terra",
                capability_tier="pro",
                context_window=128_000,
                max_output=16_384,
                input_modalities=["text"],
                tool_support=True,
                structured_output_support=True,
                reasoning_efforts=["none", "high", "max"],
                speed_class="medium",
                cost_metadata_version="session13-v1",
                availability="available",
                calibration_status="documented",
            ),
            ModelRecord(
                provider="openai",
                provider_model_id="gpt-5.6-sol",
                display_name="GPT-5.6 Sol",
                capability_tier="max",
                context_window=200_000,
                max_output=16_384,
                input_modalities=["text", "image"],
                tool_support=True,
                structured_output_support=True,
                reasoning_efforts=["none", "high", "max"],
                speed_class="slow",
                cost_metadata_version="session13-v1",
                availability="available",
                calibration_status="documented",
            ),
        ]
    )
